production:
  adapter: postgresql
  database: article_archiver_production 

development:
  adapter: postgresql
  database: article_archiver_development
  host: localhost
  username: user

test:
  adapter: postgresql
  database: article_archiver_test
